#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FILENAME="$( basename "${BASH_SOURCE[0]}" )"
PROJECTDIR="${DIR}/../../" # $DIR == ${PROJECTDIR}/.git/hooks

# Check that `HEAD` exists
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

log () {
  echo -e "$(tput setaf 8)`date -u +"%Y-%m-%dT%H:%M:%SZ"`$(tput sgr 0) - $(tput setaf 6)$FILENAME$(tput sgr 0) - $1"
}

diff_files () {
  # List files that will be changed in this commit
  git diff --diff-filter=ACMRTUXB --no-commit-id --name-only $against
}

hook () {
  log 'running hook'
  diff_files
  exec git diff-index --check --cached $against --
  exit 0
}

time hook
