#!/bin/bash

# Useful git things
#
# Show branches accessed most recently
alias git-lately="git for-each-ref --sort=-committerdate --format='%(committerdate:short) %(refname)' refs/heads refs/remotes | head"

# Prune branches that don't exist on `origin`
alias git-prune-remote="git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -d"

__git_prune_merged () {
  local base="$1"
  if [[ -z "$1" ]]; then
    echo 'Usage: git-prune-merged <base>'
    return 2
  fi

  git for-each-ref --format='%(HEAD) %(refname:strip=2)' 'refs/heads/' --merged $base \
    | grep -v '^\*' \
    | xargs git branch -d
}

# Prune branches that have been merged to master
alias git-prune-merged="__git_prune_merged $1"
